all:
  vars:
    ansible_user: vagrant
  children:
    webservers:
      vars:
      hosts:
        web01:
          ansible_host: 192.168.56.10
        web02:
          ansible_host: 192.168.56.11
    lbservers:
      vars:
      hosts:
        lb01:
          ansible_host: 192.168.56.12
    dbservers:
      vars:
      hosts:
        db01:
          ansible_host: 192.168.56.13
    monitoring:
      vars:
      hosts:
        mon01:
          ansible_host: 192.168.56.14
